<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MDS.Business\MDS.Business.csproj" />
    <ProjectReference Include="..\MDS.Data\MDS.Data.csproj" />
    <ProjectReference Include="..\MDS.Model\MDS.Model.csproj" />
  </ItemGroup>

</Project>
